export const demoCampaigns = [
  {
    id: "demo-ng",
    name: "Lagos hospitality",
    country: "NG",
    city: "Lagos",
    category: "restaurant",
    status: "active",
    resultLimit: 20,
    spentMinor: 0,
    budgetMinor: 2000,
    currency: "NGN",
    landingPagePrice: 85000,
    completeWebsitePrice: 220000,
    bookingCataloguePrice: 380000,
    complianceNote: null,
    complianceReference: null,
    approvedChannels: [],
    complianceReviewedAt: null,
  },
  {
    id: "demo-gb",
    name: "Manchester beauty",
    country: "GB",
    city: "Manchester",
    category: "salon",
    status: "active",
    resultLimit: 20,
    spentMinor: 0,
    budgetMinor: 2000,
    currency: "GBP",
    landingPagePrice: 450,
    completeWebsitePrice: 1200,
    bookingCataloguePrice: 2200,
    complianceNote: "Reviewed UK business-to-business marketing guidance.",
    complianceReference: "ICO direct marketing guidance",
    approvedChannels: ["email"],
    complianceReviewedAt: "2026-07-15T09:00:00Z",
  },
  {
    id: "demo-ca",
    name: "Toronto wellness",
    country: "CA",
    city: "Toronto",
    category: "spa",
    status: "active",
    resultLimit: 20,
    spentMinor: 0,
    budgetMinor: 2000,
    currency: "CAD",
    landingPagePrice: 650,
    completeWebsitePrice: 1750,
    bookingCataloguePrice: 3000,
    complianceNote: "Reviewed Canadian commercial messaging requirements.",
    complianceReference: "Government of Canada anti-spam guidance",
    approvedChannels: ["email", "linkedin"],
    complianceReviewedAt: "2026-07-15T09:00:00Z",
  },
];

export const demoLeads = [
  {
    id: "demo-1",
    name: "Copper & Sage Kitchen",
    category: "restaurant",
    country: "NG",
    city: "Lagos",
    score: 82,
    stage: "pitch_ready",
    websiteUrl: null,
    campaignName: "Lagos hospitality",
    suppressed: false,
  },
  {
    id: "demo-2",
    name: "Bloom Beauty Studio",
    category: "salon",
    country: "GB",
    city: "Manchester",
    score: 74,
    stage: "qualified",
    websiteUrl: "https://example.com",
    campaignName: "Manchester beauty",
    suppressed: false,
  },
  {
    id: "demo-3",
    name: "Harbour House Events",
    category: "event_venue",
    country: "NG",
    city: "Lagos",
    score: 68,
    stage: "contacted",
    websiteUrl: "https://example.com",
    campaignName: "Lagos hospitality",
    suppressed: false,
  },
  {
    id: "demo-4",
    name: "Moss & Marble Spa",
    category: "spa",
    country: "CA",
    city: "Toronto",
    score: 55,
    stage: "audited",
    websiteUrl: "https://example.com",
    campaignName: "Toronto wellness",
    suppressed: false,
  },
];
