"use client";
import { useState } from "react";
import { Check, Copy, Mail, MessageCircle, ScanSearch, ShieldX } from "lucide-react";
type Draft = { id: string; channel: "email" | "whatsapp"; subject: string | null; body: string; status: string; sentAt: string | null };
export function LeadWorkspace({ leadId, demo, canDraft, drafts: initial }: { leadId: string; demo: boolean; canDraft: boolean; drafts: Draft[] }) {
  const [drafts, setDrafts] = useState(initial); const [message, setMessage] = useState(""); const [busy, setBusy] = useState(false);
  async function run(path: string, body: object = {}) { if (demo) { setMessage("Demo data is read-only. Configure the live services first."); return null; } setBusy(true); const response = await fetch(path, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); const data = await response.json(); setBusy(false); if (!response.ok) { setMessage(data.error); return null; } return data; }
  async function audit() { const data = await run(`/api/leads/${leadId}/audit`); if (data) { setMessage(`Audit complete: ${data.audit.score}/100`); setTimeout(() => location.reload(), 700); } }
  async function draft(channel: "email" | "whatsapp") { const data = await run(`/api/leads/${leadId}/draft`, { channel }); if (data) { setDrafts((items) => [data.draft, ...items]); setMessage(`${channel} draft prepared for review.`); } }
  async function markSent(draftId: string) { const data = await run(`/api/outreach/${draftId}/mark-sent`); if (data) { setMessage("Marked sent. One follow-up is due in five business days."); setDrafts((items) => items.map((item) => item.id === draftId ? { ...item, status: "sent", sentAt: data.sentAt } : item)); } }
  async function optOut() { if (!confirm("Suppress this contact permanently?")) return; const data = await run(`/api/leads/${leadId}/opt-out`, { reason: "Contact requested no further messages" }); if (data) { setMessage("Contact permanently suppressed."); setTimeout(() => location.reload(), 600); } }
  return <div className="workspace-actions"><div className="action-bar"><button className="secondary-button compact" onClick={audit} disabled={busy}><ScanSearch size={16} />Run audit</button><button className="secondary-button compact" onClick={() => draft("email")} disabled={busy || !canDraft}><Mail size={16} />Draft email</button><button className="secondary-button compact" onClick={() => draft("whatsapp")} disabled={busy || !canDraft}><MessageCircle size={16} />Draft WhatsApp</button><button className="danger-button" onClick={optOut} disabled={busy}><ShieldX size={16} />Opt out</button></div>{message && <div className="notice">{message}</div>}<div className="draft-list">{drafts.map((item) => <article className="draft-card" key={item.id}><div className="draft-head"><span>{item.channel === "email" ? <Mail size={15} /> : <MessageCircle size={15} />}{item.channel}</span><b>{item.status}</b></div>{item.subject && <strong>{item.subject}</strong>}<pre>{item.body}</pre><div className="draft-buttons"><button className="secondary-button compact" onClick={() => navigator.clipboard.writeText(`${item.subject ? `${item.subject}\n\n` : ""}${item.body}`)}><Copy size={14} />Copy</button>{item.status === "draft" && <button className="primary-button compact" onClick={() => markSent(item.id)}><Check size={14} />I sent this</button>}</div></article>)}</div></div>;
}
